### ISSUE TITLE
How do i add the extension to chrome?

### ISSUE THREAD

**Issue by KingIdee** [emmanuelkehinde/TwittaSave-Chrome#1]
Do I have to pull the repo? And how do I build it?

**Comment by emmanuelkehinde** [comment]
To add for use, simply go to chrome extensions and search for TwittaSave and install.

To add for debugging and Testing, simply pull the repo. Open your chrome, then to your chrome extensions. Enable developer mode by ticking a small box at the top. Then select Load UnPacked Extension button, select the folder containing the extension from the file picker dialog. Then it should be loaded on your chrome.

**Comment by KingIdee** [comment]
Thanks! Good job bro!
